export const HOME = '/'
export const SIGNUP = '/signup'
export const LOGIN = '/login'
export const TRIBE = '/tribe'
export const BATTLE = '/battle'
export const PROFILE = '/profile'
export const ABOUT = '/about'
